services:
  - type: web
    name: logesco-api
    runtime: node
    rootDir: .
    buildCommand: npm ci && npx prisma generate --schema=prisma/schema.postgresql.prisma
    startCommand: chmod +x deploy-render.sh && ./deploy-render.sh && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_2AqZ4TJDMzSu@ep-flat-term-alategot-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 365d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 365d
      - key: CORS_ORIGIN
        value: "*"
      - key: LOG_LEVEL
        value: info
      - key: PORT
        value: 8080
