// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvHGJEt1u95l0rpRoQCNX_EWI1By-VSZI',
    appId: '1:499558854924:web:b35623e9d5bf5ba0b45929',
    messagingSenderId: '499558854924',
    projectId: 'logescoadmin',
    authDomain: 'logescoadmin.firebaseapp.com',
    storageBucket: 'logescoadmin.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvHGJEt1u95l0rpRoQCNX_EWI1By-VSZI',
    appId: '1:499558854924:web:9918df7d9edcc825b45929',
    messagingSenderId: '499558854924',
    projectId: 'logescoadmin',
    authDomain: 'logescoadmin.firebaseapp.com',
    storageBucket: 'logescoadmin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ5mNxsg7039OpntZOIS8FlgeOcembvHE',
    appId: '1:499558854924:android:385c286cba53a601b45929',
    messagingSenderId: '499558854924',
    projectId: 'logescoadmin',
    storageBucket: 'logescoadmin.firebasestorage.app',
  );

}